name: xsim_et
description: Ethiopia Government Portal - XSIM Authentication Mobile App
publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  google_fonts: ^6.1.0
  share_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true
  background_color_ios: "#1D6FF2"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
